### ISSUE TITLE
Error during npm install process

### ISSUE THREAD

**Issue by feluma** [beeven/node-openssl-verify-cert#1]
Hi there,

I had an issue installing the package in a new node project to test it. Looks like the issue was in the package and not the installer. Working on Mac OS.

Here the error messages:

clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/addon.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ****_mypath**_*/node_modules/node-openssl-verify-cert
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-openssl-verify-cert"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE

npm ERR! node-openssl-verify-cert@0.9.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-openssl-verify-cert@0.9.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-openssl-verify-cert package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-openssl-verify-cert
npm ERR! There is likely additional logging output above.

Hope this helps.

**Comment by beeven** [comment]
Now it can build successfully on OSX. But there are some bugs on OSX. [https://travis-ci.org/beeven/node-openssl-verify-cert](https://travis-ci.org/beeven/node-openssl-verify-cert)

Hope someone can figure it out.

**Comment by beeven** [comment]
On OS X, base64 strings in PEM file must be adjust to 64 characters per line.
